import { NodeIdentity } from "../identity/node-identity";
import { NodeCapabilities } from "../resources/resource-budget";

/**
 * WebRoom v3 — Distributed Membership Protocol Definitions & Cryptographic Verification
 * 
 * Defines wire format and message validation for signed presence and failure detection.
 */

export type MembershipMessageType = "NODE_ANNOUNCE" | "NODE_HEARTBEAT" | "NODE_GOODBYE";

export type NodeLivenessStatus = "online" | "suspected" | "offline";

export interface MembershipMessage {
  type: MembershipMessageType;
  roomId: string;
  nodeId: string;
  peerId: string;
  publicKey: string;
  signature: string;
  timestamp: number;
  sequence: number;
  status: NodeLivenessStatus;
  contributionEnabled: boolean;
  capabilities?: NodeCapabilities;
  avatar?: string;
}

const VALID_MEMBERSHIP_TYPES = new Set<MembershipMessageType>([
  "NODE_ANNOUNCE",
  "NODE_HEARTBEAT",
  "NODE_GOODBYE",
]);

const VALID_LIVENESS_STATUSES = new Set<NodeLivenessStatus>([
  "online",
  "suspected",
  "offline",
]);

export interface MembershipSignaturePayloadInput {
  type: MembershipMessageType;
  roomId: string;
  nodeId: string;
  peerId: string;
  timestamp: number;
  sequence: number;
  status: NodeLivenessStatus;
  contributionEnabled: boolean;
}

/**
 * Produces a deterministic canonical string representation of a membership message for signing/verification.
 * 
 * WHY:
 * Signing the canonical representation ensures that critical control plane fields (timestamps, sequence,
 * status, room isolation, and contribution capability) cannot be tampered with or replayed in other rooms.
 */
export function getMembershipSignaturePayload(
  msg: MembershipSignaturePayloadInput
): string {
  return [
    msg.type,
    msg.roomId,
    msg.nodeId,
    msg.peerId,
    msg.timestamp,
    msg.sequence,
    msg.status,
    msg.contributionEnabled ? "1" : "0",
  ].join(":");
}

/**
 * Validates the structural integrity and type correctness of an incoming membership message object.
 */
export function isValidMembershipMessage(
  payload: unknown,
  expectedRoomId?: string
): payload is MembershipMessage {
  if (!payload || typeof payload !== "object") {
    return false;
  }

  const candidate = payload as Record<string, unknown>;

  if (
    typeof candidate.type !== "string" ||
    !VALID_MEMBERSHIP_TYPES.has(candidate.type as MembershipMessageType)
  ) {
    return false;
  }

  if (typeof candidate.roomId !== "string" || candidate.roomId.trim().length === 0) {
    return false;
  }

  if (expectedRoomId && candidate.roomId !== expectedRoomId) {
    return false;
  }

  if (
    typeof candidate.nodeId !== "string" ||
    !candidate.nodeId.startsWith("node_") ||
    candidate.nodeId.trim().length < 10
  ) {
    return false;
  }

  if (typeof candidate.peerId !== "string" || candidate.peerId.trim().length === 0) {
    return false;
  }

  if (typeof candidate.publicKey !== "string" || candidate.publicKey.trim().length === 0) {
    return false;
  }

  if (typeof candidate.signature !== "string" || candidate.signature.trim().length === 0) {
    return false;
  }

  if (
    typeof candidate.timestamp !== "number" ||
    isNaN(candidate.timestamp) ||
    candidate.timestamp <= 0
  ) {
    return false;
  }

  if (
    typeof candidate.sequence !== "number" ||
    isNaN(candidate.sequence) ||
    candidate.sequence < 0
  ) {
    return false;
  }

  if (
    typeof candidate.status !== "string" ||
    !VALID_LIVENESS_STATUSES.has(candidate.status as NodeLivenessStatus)
  ) {
    return false;
  }

  if (typeof candidate.contributionEnabled !== "boolean") {
    return false;
  }

  if (
    candidate.avatar !== undefined &&
    (typeof candidate.avatar !== "string" || candidate.avatar.trim().length === 0)
  ) {
    return false;
  }

  return true;
}

/**
 * Cryptographically verifies that the message signature was generated by the owner of the public key.
 */
export async function verifyMembershipMessageSignature(
  msg: MembershipMessage
): Promise<boolean> {
  const canonicalPayload = getMembershipSignaturePayload(msg);
  return NodeIdentity.verifySignature(canonicalPayload, msg.signature, msg.publicKey);
}
